name: "Slack Build"
on:
  workflow_dispatch:

jobs:
  package:
    strategy:
      matrix:
        platform: [windows-latest, macos-14, ubuntu-latest]
        go-version: [1.22]
        arch: [amd64, arm64]
        exclude:
          - platform: windows-latest
            arch: arm64
          - platform: ubuntu-latest
            arch: arm64
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies on Linux
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential libgtk-3-dev libpcap-dev libwebkit2gtk-4.1-dev

      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.9.2

      - name: Build Wails app on Ubuntu
        if: matrix.platform == 'ubuntu-latest' && matrix.arch == 'amd64'
        run: wails build -tags webkit2_41 -platform linux/amd64

      - name: Build Wails app on macOS
        if: matrix.platform == 'macos-14'
        run: wails build -platform darwin/${{ matrix.arch }}

      - name: Build Wails app on Windows
        if: matrix.platform == 'windows-latest' && matrix.arch == 'amd64'
        run: wails build -platform windows/amd64

      - name: Upload Artifacts macOS
        if: matrix.platform == 'macos-14'
        uses: actions/upload-artifact@v4
        with:
          name: Slack-macos-${{ matrix.arch }}
          path: build/bin/*

      - name: Upload Artifacts Windows
        if: matrix.platform == 'windows-latest' && matrix.arch == 'amd64'
        uses: actions/upload-artifact@v4
        with:
          name: Slack-windows-amd64
          path: build/bin/*

      - name: Upload Artifacts Linux
        if: matrix.platform == 'ubuntu-latest' && matrix.arch == 'amd64'
        uses: actions/upload-artifact@v4
        with:
          name: Slack-linux-amd64
          path: build/bin/*
